services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: lcc-tools
    restart: unless-stopped
    ports:
      - "8701:8701"
    environment:
      - LCC_HOST=10.89.11.52
      - LCC_CLIENT_ID=iuta-notification
      - LCC_CLIENT_SECRET=YF72ojKY99U
      - OPC_URL=opc.tcp://10.89.11.52:4840
    volumes:
      - ./config:/app/config
      - ./data:/app/data

  frontend:
    build: ./frontend
    container_name: lcc-tools-frontend
    restart: unless-stopped
    ports:
      - "8999:80"
    depends_on:
      - api
